- hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: add node repo
      shell:
        cmd: curl -fsSL https://rpm.nodesource.com/setup_16.x | sudo bash - # not required. The command to run followed by optional arguments.
    - name: add node repo
      yum_repository:
        name: mongodb
        description: add mongo repo
        baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.2/x86_64/
        gpgkey: https://www.mongodb.org/static/pgp/server-4.2.asc
        enabled: true
    - name: install epel repo
      yum:
        name: oracle-epel-release-el8.x86_64
        state: present
    - name: run yum update
      yum:
        name: '*'
        state: latest
    - name: install node
      yum:
        name: npm
        state: present
    - name: install mongodb client
      yum: 
        name: mongodb-org
        state: present
    - name: enable and start mongo service
      service:
        name: mongod
        state: started
        enabled: true
        